### ISSUE TITLE
'yarn run:host:android' show only loading page.

### ISSUE THREAD

**Issue by JeehoonLim** [callstack/super-app-showcase#49]
## Ask your Question

Hello.
I tried to execute your showcase without standalone .
I open 3 terminals and execute like below, but what I can see is only the loading page.

Term 1: yarn
        yarn start
Term 2: yarn adbreverse
Term 3: yarn run:host:android

Do I need something more to run the superapp and miniapps?

<img width="985" alt="repack" src="https://github.com/callstack/super-app-showcase/assets/25518208/1245ca26-5c69-4dba-97d8-1a9f76337692">

**Comment by thymikee** [comment]
You will also need to run the catalog-server and auth module:
```
yarn concurrently -P "yarn start:catalog" "yarn start:auth"
```
Does that work for you?

**Comment by JeehoonLim** [comment]
When I execute the coomand, It gives me errors like below.

> [0] Error: listen EADDRINUSE: address already in use :::3000
> ...
> [0] yarn start:catalog exited with code 1
> [1] error listen EADDRINUSE: address already in use ::1:9003.

I guess the cause is that first command 'yarn start' already run  the catalog-server and auth module:

> PS C:\work\repack\super-app-showcase> yarn start
> [catalog] [CatalogServer] Server listening at port 3000
> [shopping] i [20:12:31.181Z][DevServer] Server listening at http://[::1]:9001
> [booking] i [20:12:31.388Z][DevServer] Server listening at http://[::1]:9000
> [dashboard] i [20:12:31.517Z][DevServer] Server listening at http://[::1]:9002
> [auth] i [20:12:31.516Z][DevServer] Server listening at http://[::1]:9003
> [host] i [20:12:31.806Z][DevServer] Server listening at http://[::1]:8081

**Comment by trancongdung12** [comment]
any update? same issue when run app

**Comment by aravindle** [comment]
> any update? same issue when run app

same here

**Comment by jbroma** [comment]
Hi everyone,

I've recently updated Re.Pack and CodeSigning configuration, please check whether this resolves your issues!

Regarding the commands, the only commands you should need for running the app on Android should be this:
```sh
yarn start                 # starts all the devservers
yarn run:host:android      # builds the app for android & starts the emulator
yarn adbreverse            # enables connection via ports needed by the devservers
```

One word of advice - you need to run `yarn adbreverse` after the emulator has started, otherwise it will have no effect.

**Comment by keila66** [comment]
Im having this same issue when running app on Windows 11. Any possible solution?

**Comment by quangtruongdit** [comment]
Hi all, 

I have got the issue with run the app on Android device as below, seems the Auth module does not get bundle correctly.
Do you guys have same issue?

`⇢ [03:01:01.815Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 192/234 dependencies 13/106 modules) 
⇢ [03:01:04.198Z][LoggerPlugin] Compiling android: 31% building (4/10 entries 826/1000 dependencies 87/290 modules) 
⇢ [03:01:05.884Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 1631/1700 dependencies 126/450 modules) 
⇢ [03:01:08.153Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2113/2200 dependencies 187/543 modules) 
⇢ [03:01:09.921Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2717/3000 dependencies 287/597 modules) 
⇢ [03:01:12.506Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2898/3139 dependencies 318/600 modules) 
⇢ [03:01:13.890Z][LoggerPlugin] Compiling android: 65% building (14/14 entries 3908/3908 dependencies 762/762 modules) 
node:internal/event_target:1010
  process.nextTick(() => { throw err; });
                           ^

Error: ENOENT: no such file or directory, open '/Users/../reactnative/rn-super-app/packages/auth/build/generated/android/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js.chunk.bundle'
Emitted 'error' event on Compiler instance at:
    at Worker.<anonymous> (/Users/.../reactnative/rn-super-app/packages/auth/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
`

I temporary removed the 'auth' from the host app, then I am able to run this app with the 'booking' module.

Thanks

**Comment by quangtruongdit** [comment]
> ## Ask your Question
> Hello. I tried to execute your showcase without standalone . I open 3 terminals and execute like below, but what I can see is only the loading page.
> 
> Term 1: yarn yarn start Term 2: yarn adbreverse Term 3: yarn run:host:android
> 
> Do I need something more to run the superapp and miniapps?
> 
> <img alt="repack" width="985" src="https://user-images.githubusercontent.com/25518208/250552948-1245ca26-5c69-4dba-97d8-1a9f76337692.png">

Please try to remove "AuthProvider" in the host/src/App.tsx. Seems 'auth' module has some issue with bundling.

Try return this component only.
`return (
              <NavigationContainer onReady={() => RNBootSplash.hide({ fade: true, duration: 500 })}>
                <MainNavigator />
              </NavigationContainer>
            );`

**Comment by aravindd7** [comment]
> Hi all, 
> I have got the issue with run the app on Android device as below, seems the Auth module does not get bundle correctly.
> Do you guys have same issue?
> 
> `
> ⇢ [03:01:01.815Z][LoggerPlugin] Compiling android: 26% building (3/10 entries 192/234 dependencies 13/106 modules) 
> ⇢ [03:01:04.198Z][LoggerPlugin] Compiling android: 31% building (4/10 entries 826/1000 dependencies 87/290 modules) 
> ⇢ [03:01:05.884Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 1631/1700 dependencies 126/450 modules) 
> ⇢ [03:01:08.153Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2113/2200 dependencies 187/543 modules) 
> ⇢ [03:01:09.921Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2717/3000 dependencies 287/597 modules) 
> ⇢ [03:01:12.506Z][LoggerPlugin] Compiling android: 32% building (4/10 entries 2898/3139 dependencies 318/600 modules) 
> ⇢ [03:01:13.890Z][LoggerPlugin] Compiling android: 65% building (14/14 entries 3908/3908 dependencies 762/762 modules) 
> node:internal/event_target:1010
>   process.nextTick(() => { throw err; });
>                            ^
> 
> Error: ENOENT: no such file or directory, open '/Users/../reactnative/rn-super-app/packages/auth/build/generated/android/vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_lib_runtime_RefreshUtils_js.chunk.bundle'
> Emitted 'error' event on Compiler instance at:
>     at Worker.<anonymous> (/Users/.../reactnative/rn-super-app/packages/auth/node_modules/@callstack/repack/dist/webpack/Compiler.js:110:14)
>     at Worker.emit (node:events:513:28)
>     at MessagePort.<anonymous> (node:internal/worker:233:53)
>     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
>     at exports.emitMessage (node:internal/per_context/messageport:23:28)
> `
> 
> I temporary removed the 'auth' from the host app, then I am able to run this app with the 'booking' module.
> 
> Thanks
> 

What all steps did u take to remove auth from the host app. Could you please tell me as I am trying to boot this project since few weeks.

**Comment by quangtruongdit** [comment]
> . Could you

There are 2 things I did:
1. Create a pem file called 'code-signing.pem' and place it in root folder 
2. Go to ./packages/host/src/App.tsx, then remove the 'AuthProvider"
Your code in App.tsx now is:

`import React from 'react';
import RNBootSplash from "react-native-bootsplash";
import {Federated} from '@callstack/repack/client';
import {NavigationContainer} from '@react-navigation/native';
import MainNavigator from './navigation/MainNavigator';
import SplashScreen from './components/SplashScreen';
import ErrorBoundary from './components/ErrorBoundary';

const AuthProvider = React.lazy(() =>
  Federated.importModule('auth', './AuthProvider'),
);
const SignInScreen = React.lazy(() =>
  Federated.importModule('auth', './SignInScreen'),
);

const App = () => {
  return (
    <NavigationContainer onReady={() => RNBootSplash.hide({ fade: true, duration: 500 })}>
      <MainNavigator />
    </NavigationContainer>
  );
};

export default App;
`
3. Follow the readme and start app as normal

At root folder:
- yarn
- yarn start
- yarn run:host:android
- yarn adbreverse

Hope it helps

**Comment by umer4081** [comment]
Im having this same issue when running app please any new update here!!

**Comment by aravindd7** [comment]
> Im having this same issue when running app please any new update here!!

I shifted to Linux OS and could get the app to work based on inputs from all issue threads

**Comment by umer4081** [comment]
I'm not getting your point could you please explain!
________________________________

**Comment by umer4081** [comment]
![Screenshot 2023-09-09 at 3 58 16 PM](https://github.com/callstack/super-app-showcase/assets/143785399/085750bd-7726-46b5-8d3a-ab758c4f8271)

**Comment by JeehoonLim** [comment]
I should share my current status.
I could see the app screens when I execute on Macbook env, failed with windows env.

**< History of my work > **
I use 3 environment for this showcase

**Env 1:  Old Windows Laptop ( For 1st try )**
 It stucked with loading page.    --> I assume the problem is due to lack of resources.
 
 **Env 2:  New Windows Laptop**
 I could pass the 'Loading page issue'.
 But the app show me ESM Loader error like #63.
 	
_[host] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'_ 	

I received recent branch from the repository, but the problem was not solved. 
I think this problem is related to [this reapck issue](https://github.com/callstack/repack/issues/215).

    
 **Env3:  (Old) Macbook**
Finally,  I could see the app screens.
In fact, when first execution of every app - host ans mini app -,  It shows me the error page.
But second request - after build complete, it works well.

**Comment by aravindd7** [comment]
Same with me(env3 case)

**Comment by bharath-doijode** [comment]
I also had the same `show only loading page` issue. Now it is resolved by changing to below environment

Node Version: v18.11.0
repack module version:  "@callstack/repack": "~3.7.0",
OS: mac

**Comment by Akshayn777** [comment]
Hey,
I facing the issue like , When I try to run the react native app. I can able to install the app and I can also able to see the splash screen. but somehow the development server disconnects. Please give me a solution.
node version :21.0.0

![Screenshot_1709214657](https://github.com/callstack/super-app-showcase/assets/68912897/476f9e10-8278-45f5-a990-165ae1a39813)

**Comment by bharath-doijode** [comment]
> Hey, I facing the issue like , When I try to run the react native app. I can able to install the app and I can also able to see the splash screen. but somehow the development server disconnects. Please give me a solution. node version :21.0.0
> 
> PC : Windows
> 
> ![Screenshot_1709214657](https://private-user-images.githubusercontent.com/68912897/309637138-476f9e10-8278-45f5-a990-165ae1a39813.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzkyOTksIm5iZiI6MTcwOTUzODk5OSwicGF0aCI6Ii82ODkxMjg5Ny8zMDk2MzcxMzgtNDc2ZjllMTAtODI3OC00NWY1LWE5OTAtMTY1YWUxYTM5ODEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA3NTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZWE5OTUzZWUyNTViMTMwMGYzOThmY2EzZjMwNmE5ODY4YzMzNmViYzc1YTZjMzIzM2Y4MjRmNDczOTU1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cB5XLsew9yD9uXpP4OJ6I3Pbwhkm8eVHMnjZVzuOMiE)

Please downgrade the node version to 18.x.x and try

**Comment by Havanika28** [comment]
hi, 
@bharath-doijode Downgrading the version dint work. I am still seeing the same callstack screen.
Please help.

**Comment by trancongdung12** [comment]
@quangtruongdit Have you built a super app yet? bro 🇻🇳
