### ISSUE TITLE
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

### ISSUE THREAD

**Issue by le-thi-le** [callstack/super-app-showcase#63]
## Environment

debug

## Description

 I try run this project in window 11 and debug in real device (Xiaomi note 11pro) but it show error
[catalog] [CatalogServer] Server listening at port 3000
[booking] i [09:58:28.627Z][DevServer] Server listening at http://127.0.0.1:9000
[shopping] i [09:58:28.632Z][DevServer] Server listening at http://127.0.0.1:9001
[dashboard] i [09:58:28.644Z][DevServer] Server listening at http://127.0.0.1:9002
[auth] i [09:58:28.648Z][DevServer] Server listening at http://127.0.0.1:9003
[host] i [09:58:28.708Z][DevServer] Server listening at http://127.0.0.1:8081
[host] i [09:58:29.077Z][DevServer] Hermes device connected { deviceId: 0 }
[host] i [09:58:29.079Z][DevServer] Hermes device connected { deviceId: 1 }
[host] i [09:58:30.071Z][DevServer] Hermes device connected { deviceId: 2 }
[host] i [09:59:26.067Z][DevServer] Hermes device disconnected { deviceId: 0 } 
[host] i [09:59:27.486Z][DevServer] Hermes device connected { deviceId: 3 } 
[host] i [09:59:27.579Z][DevServer] GET 200 /status request completed { responseTime: 3.962899997830391 } 
[host] node:internal/event_target:912
[host]   process.nextTick(() => { throw err; });
[host]                            ^
[host] 
[host] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
[host]     at new NodeError (node:internal/errors:372:5)
[host]     at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
[host]     at defaultResolve (node:internal/modules/esm/resolve:1200:3)
[host]     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
[host]     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
[host]     at ESMLoader.import (node:internal/modules/esm/loader:380:22)
[host]     at importModuleDynamically (node:internal/modules/cjs/loader:1043:29)
[host]     at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
[host]     at importModuleDynamically (node:vm:381:46)
[host]     at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
[host] Emitted 'error' event on Compiler instance at:
[host]     at Worker.<anonymous> (D:\lele\super-app-showcase\packages\host\node_modules\@callstack\repack\dist\webpack\Compiler.js:110:14)
[host]     at Worker.emit (node:events:527:28)
[host]     at MessagePort.<anonymous> (node:internal/worker:232:53)
[host]     at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
[host]     at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
[host] yarn run start:host  exited with code 1

----------------------------- my version in local device------------------------
node:  v16.15.0
yarn: 3.2.1
webback: 8.5.5
-----------------------------------------------------------------------------
Please suport me or Can you tell me I am missing config or environment? Thank you so much!

**Comment by le-thi-le** [comment]
I see it also standing at the loading screen like in the issue https://github.com/callstack/super-app-showcase/issues/49

**Comment by umer4081** [comment]
thank you so much this code is now working fine as I changed App name and remove splash  screen and app icon and I do some changes catalog-server !!

**Comment by akshay-capgemini** [comment]
I have the issue while run the app.

node:internal/event_target:1084
  process.nextTick(() => { throw err; });
                           ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:226:11)
    at defaultLoad (node:internal/modules/esm/load:128:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:409:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:56)
    at new ModuleJob (node:internal/modules/esm/module_job:65:26)
    at #createModuleJob (node:internal/modules/esm/loader:303:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:260:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:241:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:328:23)
Emitted 'error' event on Compiler instance at:
    at Worker.<anonymous> (C:\reactnative\super-app-showcase\node_modules\.pnpm\@callstack+repack@3.4.0_@react-native-community+cli-types@12.3.6_@react-native-community+cli@_6a5gwxs3mkufiqvo4ht3wbx6pe\node_modules\@callstack\repack\dist\webpack\Compiler.js:110:14)
    at Worker.emit (node:events:515:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:810:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v21.0.0

**Comment by apatheticL** [comment]
Hello @akshay-capgemini.  I think problem is node in Window OS. I tried every case but it not work in window but i change system use MacOS then it work. You can try it. I haven't been able to find out the reason why it not work in window.

**Comment by umer4081** [comment]
> thank you so much this code is now working fine as I changed App name and remove splash screen and app icon and I do some changes catalog-server !!

**Comment by ckbroooo** [comment]
Anyone found a solutions to this problem? so far it only solvable by changing window os to linux os or mac os.
